name: build-poncho

on:
  push:
    branches:
      - release-1.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out release-1.x
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: ./poncho
          ref: release-1.x
      - name: 🎩 Compilamos todo
        working-directory: ./poncho
        run: |
          npm install
          npm run gulp
      - name: Checkout Iconos Arg
        uses: actions/checkout@v4
        with: 
          repository: argob/iconos
          path: ./iconos
      - name: Copy/Create file
        run: |
          echo "Copying $FILE"
          rm -f ./poncho/dist/fonts/icono-arg_*
          cp -R ./iconos/dist/css/icono-arg.css ./poncho/dist/css/
          echo "Listamos fuentes de Iconos"
          ls ./iconos/dist/fonts/
          cp ./iconos/dist/fonts/icono-arg_* ./poncho/dist/fonts/
          echo "Copiamos las ilustraciones"
          cp -R ./iconos/dist/ilustraciones ./poncho/dist/
          echo "Copiamos el JSON de los íconos e ilustraciones"
          mkdir -p ./poncho/dist/jsons
          cp ./iconos/docs/icono-arg.json ./poncho/dist/jsons/
          cp ./iconos/docs/ilus-arg.json ./poncho/dist/jsons/
          echo "Listamos fuentes de Poncho"
          ls ./poncho/dist/fonts/
      - name: 🧪 Deploy build
        working-directory: ./poncho
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --force -- dist/*
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
